import os
import pandas as pd
import numpy as np
# cwdd = os.getcwd()
# print(cwdd)
inputData=pd.read_csv(r'C:\Users\sshivar4\Desktop\Data Mining\Project-1-Files-1\Project 1 Student Files\CGMData.csv',low_memory=False,usecols=['Date','Time','Sensor Glucose (mg/dL)'])
insulinData=pd.read_csv(r'C:\Users\sshivar4\Desktop\Data Mining\Project-1-Files-1\Project 1 Student Files\InsulinData.csv',low_memory=False)
inputData['date_time_stamp']=pd.to_datetime(inputData['Date'] + ' ' + inputData['Time'])
date_to_remove=inputData[inputData['Sensor Glucose (mg/dL)'].isna()]['Date'].unique()
inputData=inputData.set_index('Date').drop(index=date_to_remove).reset_index()
cgm_test=inputData.copy()
cgm_test=cgm_test.set_index(pd.DatetimeIndex(inputData['date_time_stamp']))
insulinData['date_time_stamp']=pd.to_datetime(insulinData['Date'] + ' ' + insulinData['Time'])
sort_values_auto_mode=insulinData.sort_values(by='date_time_stamp',ascending=True).loc[insulinData['Alarm']=='AUTO MODE ACTIVE PLGM OFF'].iloc[0]['date_time_stamp']
data_frame_auto_mode=inputData.sort_values(by='date_time_stamp',ascending=True).loc[inputData['date_time_stamp']>=sort_values_auto_mode]
manual_mode_data_df=inputData.sort_values(by='date_time_stamp',ascending=True).loc[inputData['date_time_stamp']<sort_values_auto_mode]
data_frame_auto_mode_date_index=data_frame_auto_mode.copy()
data_frame_auto_mode_date_index=data_frame_auto_mode_date_index.set_index('date_time_stamp')
list_count1=data_frame_auto_mode_date_index.groupby('Date')['Sensor Glucose (mg/dL)'].count().where(lambda x:x>0.8*288).dropna().index.tolist()
data_frame_auto_mode_date_index=data_frame_auto_mode_date_index.loc[data_frame_auto_mode_date_index['Date'].isin(list_count1)]
percent_time_in_hyperglycemia_wholeday_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_daytime_automode=(data_frame_auto_mode_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_overnight_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_critical_wholeday_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_critical_daytime_automode=(data_frame_auto_mode_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_critical_overnight_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_wholeday_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>=70) & (data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_daytime_automode=(data_frame_auto_mode_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>=70) & (data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_overnight_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>=70) & (data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_sec_wholeday_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>=70) & (data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_sec_daytime_automode=(data_frame_auto_mode_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>=70) & (data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_sec_overnight_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']>=70) & (data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv1_wholeday_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv1_daytime_automode=(data_frame_auto_mode_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv1_overnight_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv2_wholeday_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv2_daytime_automode=(data_frame_auto_mode_date_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv2_overnight_automode=(data_frame_auto_mode_date_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[data_frame_auto_mode_date_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
manual_mode_data_df_index=manual_mode_data_df.copy()
manual_mode_data_df_index=manual_mode_data_df_index.set_index('date_time_stamp')
list_count2=manual_mode_data_df_index.groupby('Date')['Sensor Glucose (mg/dL)'].count().where(lambda x:x>0.8*288).dropna().index.tolist()
manual_mode_data_df_index=manual_mode_data_df_index.loc[manual_mode_data_df_index['Date'].isin(list_count2)]
percent_time_in_hyperglycemia_wholeday_manual=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_daytime_manual=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_overnight_manual=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>180].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_critical_wholeday_manual=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_critical_daytime_manual=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hyperglycemia_critical_overnight_manual=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']>250].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_wholeday_manual=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_daytime_manual=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_overnight_manual=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=180)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_sec_wholeday_manual=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_sec_daytime_manual=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_range_sec_overnight_manual=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[(manual_mode_data_df_index['Sensor Glucose (mg/dL)']>=70) & (manual_mode_data_df_index['Sensor Glucose (mg/dL)']<=150)].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv1_wholeday_manual=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv1_daytime_manual=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv1_overnight_manual=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<70].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv2_wholeday_manual=(manual_mode_data_df_index.between_time('0:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv2_daytime_manual=(manual_mode_data_df_index.between_time('6:00:00','23:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
percent_time_in_hypoglycemia_lv2_overnight_manual=(manual_mode_data_df_index.between_time('0:00:00','05:59:59')[['Date','Time','Sensor Glucose (mg/dL)']].loc[manual_mode_data_df_index['Sensor Glucose (mg/dL)']<54].groupby('Date')['Sensor Glucose (mg/dL)'].count()/288*100)
results_df = pd.DataFrame({'percent_time_in_hyperglycemia_overnight':[ percent_time_in_hyperglycemia_overnight_manual.mean(axis=0),percent_time_in_hyperglycemia_overnight_automode.mean(axis=0)],
'percent_time_in_hyperglycemia_critical_overnight':[ percent_time_in_hyperglycemia_critical_overnight_manual.mean(axis=0),percent_time_in_hyperglycemia_critical_overnight_automode.mean(axis=0)],
'percent_time_in_range_overnight':[ percent_time_in_range_overnight_manual.mean(axis=0),percent_time_in_range_overnight_automode.mean(axis=0)],
'percent_time_in_range_sec_overnight':[ percent_time_in_range_sec_overnight_manual.mean(axis=0),percent_time_in_range_sec_overnight_automode.mean(axis=0)],
'percent_time_in_hypoglycemia_lv1_overnight':[ percent_time_in_hypoglycemia_lv1_overnight_manual.mean(axis=0),percent_time_in_hypoglycemia_lv1_overnight_automode.mean(axis=0)],
'percent_time_in_hypoglycemia_lv2_overnight':[ np.nan_to_num(percent_time_in_hypoglycemia_lv2_overnight_manual.mean(axis=0)),percent_time_in_hypoglycemia_lv2_overnight_automode.mean(axis=0)],
                           'percent_time_in_hyperglycemia_daytime':[ percent_time_in_hyperglycemia_daytime_manual.mean(axis=0),percent_time_in_hyperglycemia_daytime_automode.mean(axis=0)],
                           'percent_time_in_hyperglycemia_critical_daytime':[ percent_time_in_hyperglycemia_critical_daytime_manual.mean(axis=0),percent_time_in_hyperglycemia_critical_daytime_automode.mean(axis=0)],
                           'percent_time_in_range_daytime':[ percent_time_in_range_daytime_manual.mean(axis=0),percent_time_in_range_daytime_automode.mean(axis=0)],
                           'percent_time_in_range_sec_daytime':[ percent_time_in_range_sec_daytime_manual.mean(axis=0),percent_time_in_range_sec_daytime_automode.mean(axis=0)],
                           'percent_time_in_hypoglycemia_lv1_daytime':[ percent_time_in_hypoglycemia_lv1_daytime_manual.mean(axis=0),percent_time_in_hypoglycemia_lv1_daytime_automode.mean(axis=0)],
                           'percent_time_in_hypoglycemia_lv2_daytime':[ percent_time_in_hypoglycemia_lv2_daytime_manual.mean(axis=0),percent_time_in_hypoglycemia_lv2_daytime_automode.mean(axis=0)],                      
                           'percent_time_in_hyperglycemia_wholeday':[ percent_time_in_hyperglycemia_wholeday_manual.mean(axis=0),percent_time_in_hyperglycemia_wholeday_automode.mean(axis=0)],
                           'percent_time_in_hyperglycemia_critical_wholeday':[ percent_time_in_hyperglycemia_critical_wholeday_manual.mean(axis=0),percent_time_in_hyperglycemia_critical_wholeday_automode.mean(axis=0)],
                           'percent_time_in_range_wholeday':[ percent_time_in_range_wholeday_manual.mean(axis=0),percent_time_in_range_wholeday_automode.mean(axis=0)],
                           'percent_time_in_range_sec_wholeday':[ percent_time_in_range_sec_wholeday_manual.mean(axis=0),percent_time_in_range_sec_wholeday_automode.mean(axis=0)],
                           'percent_time_in_hypoglycemia_lv1_wholeday':[ percent_time_in_hypoglycemia_lv1_wholeday_manual.mean(axis=0),percent_time_in_hypoglycemia_lv1_wholeday_automode.mean(axis=0)],
                           'percent_time_in_hypoglycemia_lv2_wholeday':[ percent_time_in_hypoglycemia_lv2_wholeday_manual.mean(axis=0),percent_time_in_hypoglycemia_lv2_wholeday_automode.mean(axis=0)]},index=['manual_mode','auto_mode'])
results_df.to_csv(r'C:\Users\sshivar4\Desktop\Data Mining\Project-1-Files-1\Project 1 Student Files\Results.csv',header=False,index=False)
